apiVersion: v1
kind: PersistentVolume
metadata:
 finalizers:
 - kubernetes.io/pv-protection
 name: jobservice-pv-volume
spec:
 accessModes:
 - ReadWriteOnce
 capacity:
   storage: 2Gi
 hostPath:
   # local path on my machine
   path: /data/harbor/data/jobservice-pv
   type: DirectoryOrCreate
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-path
 volumeMode: Filesystem
