apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jobservice-pvc
 namespace: harbor
spec:
 accessModes:
 - ReadWriteOnce
 storageClassName: local-path
 resources:
   requests:
     storage: 2Gi
 volumeName: jobservice-pv-volume
