apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: trivy-pvc
 namespace: harbor
spec:
 accessModes:
 - ReadWriteOnce
 storageClassName: local-path
 resources:
   requests:
     storage: 2Gi
 volumeName: trivy-pv-volume
